---
title: "Influence of games on cooperative behaviours. Metaanalysis."
shorttitle: "Games on cooperative behaviours"
author:
  - name: Paweł Kleka
    corresponding: true
    orcid: 0000-0003-0841-0015
    email: pawel.kleka@amu.edu.pl
    url: https://kleka.web.amu.edu.pl
    # Roles are optional. 
    # Select from the CRediT: Contributor Roles Taxonomy https://credit.niso.org/
    # conceptualization, data curation, formal Analysis, funding acquisition, investigation, 
    # methodology, project administration, resources, software, supervision, validation, 
    # visualization, writing, editing
    roles:
      - conceptualization
      - writing
    affiliation: 
      - id: uam
        name: Adam Mickiewicz University in Poznan
        department: Wydział Psychologii i Kognitywistyki 
        postal-code: 60-712
        address: ul. Wieniawskiego 1
        city: Poznań
      - id: uz
        name: Uniwersytet Zielonogórski
        department: Wydział Nauk Społecznych, Instytut Psychologii
        postal-code: 55-040
        address: ul. Licealna 2
        city: Zielona Góra
  - name: Agnieszka Smolnicka
    email: agnieszka.smolnicka@amu.edu.pl
    roles: 
      - data curation
      - editing
    affiliation: 
      - ref: uam
  - name: Agnieszka Szostak
    roles: 
      - conceptualization
    affiliation: Poznań
draft-date: true
date: last-modified
blank-lines-above-author-note: 2
author-note:
  status-changes: 
    affiliation-change: ~
    deceased: ~
  disclosures:
    study-registration: ~
    data-sharing: ~
    related-report: ~
    conflict-of-interest: ~
    financial-support: ~
    gratitude: ~
    authorship-agreements: ~
abstract: "
  **Objective**. tap tap
  **Methods**. tap tap
  **Results**. tap tap
  **Conclusions**. tap"
keywords: [cooperative games, prosocial behaviours]
bibliography: [references/bibliografia.2.0.bib]
word-count: false
floatsintext: true
numbered-lines: false          # Numbered lines (.pdf and .docx only)
suppress-title-page: false     # Suppress title page
link-citations: true           # Link citations to references
mask: false                    # Masks references that appear in the masked-citations list
masked-citations: 
  - ~
# Language options. See https://quarto.org/docs/authoring/language.html
lang: en
language:
  citation-last-author-separator: "and"
  title-block-author-note: "Author Note"
  title-block-correspondence-note: "Correspondence concerning this article should be addressed to"
  title-block-role-introduction: "Author roles were classified using the Contributor Role Taxonomy (CRediT; [credit.niso.org](https://credit.niso.org)) as follows:"
  title-impact-statement: "Impact Statement"
  references-meta-analysis: "References marked with an asterisk indicate studies included in the meta-analysis."
# Output format
format:
#  apaquarto-docx: default
  apaquarto-pdf:
    documentmode: man
    keep-tex: false
---


```{r setup, include = FALSE}
options(knitr.kable.digits = 2, knitr.kable.na = '')
knitr::opts_chunk$set(cache.extra = knitr::rand_seed,
                      echo = F,
                      fig.width = 7,
                      fig.height = 5,
                      fig.align = 'center',
                      # out.width = "100%",
                      dev = "svg",
                      cache = TRUE)

mojekolory <- c("royalblue4", "firebrick4", "#51315E")

```


The video games industry has grown significantly over the last few decades.
According to the 2021 Newzoo report, the game market is now worth \$175.8 billion, and there are over 3 billion gamers worldwide.
Video games are popular, diverse, easily accessible, and played by people of all ages and nationalities.
Respectively has been growing the research around the game's influence on human behavior, cognition, and affect.
Initially, researchers focused mainly on the antisocial effects of playing video games.
In 2010 Anderson et al. published the first meta-analysis on the effects of playing video games.
They studied the effects of playing violent video games on aggressive behavior, aggressive cognition, aggressive affect, physiological arousal, empathy, and prosocial behavior.
As expected, playing violent video games turned out to be a causal risk factor for aggressive behavior, cognition, and affect.
It was also related to lower empathy and prosocial behavior (Anderson, 2010).
The first meta-analysis that examined the prosocial effects of playing video games was published in 2014 by Greitemyer and Mügge.
The results showed that as violent video games increase aggression-related variables, prosocial games have the opposite effect (Greitemyer and Mügge, 2014).
These studies solemnly focused on the content of video games.
As a framework, they commonly used the General Learning Model.
This theory predicts that interacting with video game content can have short-term and long-term effects (Buckley & Anderson, 2010).
Games provide models, reinforce certain behaviors, and primes prosocial or antisocial cognitive scripts.
GML describes how repeated exposure to playing video games may lead to long-term changes in behavior and cognition by influencing attitudes, schemas, and affective traits.
However, this approach leaves out one vital aspect, the context of playing the game.
Some studies in recent years showed that playing the same game cooperatively, alone, or competitively has a different effect on the player.
For example, Jerabeck & Ferguson's (2013) study examined how the content and context of the game influence the aggressive or prosocial behavior of the players.
Gathered data indicated that: "Playing cooperatively was associated with less aggressive behavior, whether games were violent or not"(Jerabeck, Ferguson, 2013).
Therefore in this meta-analysis, we decided to study both cooperative and prosocial games to address the distinction between content and context of gameplay and examine how those two factors intertwine and impact prosocial behavior.

## Current study

According to Daniel Batson, prosocial behaviors refer to "a broad range of actions intended to benefit one or more people other than oneself---behaviors such as helping, comforting, sharing and cooperation."(2003, p.463).
In my experience, we can talk about two types of prosocial games.
Firstly, there are prosocial games that are prosocial by design.
The mechanics, the plot, and the goal of those games are coherent and intend to promote prosocial change in players.
Secondly, we can find a significant amount of commercial games that have prosocial effects on players, without that ever being their main intention.
They usually have some prosocial content (e.g. mechanics, story, goal, or role) or context (playing cooperatively).
The key fact to remember is that we can not put a simple distinction between prosocial, neutral, and antisocial games.
For instance, there are games where you cooperate with other players in your team, but you fight against other teams or games where you use violence, but the main goal is to save the world.
As there is no objective way of distinguishing which games are prosocial enough to be included, we decided to trust the authors of the original studies that the games they chose are indeed prosocial.

# Methods

We report how we determined our sample size, all data exclusions (if any), all manipulations, and all measures in the study.
<!-- 21-word solution (Simmons, Nelson & Simonsohn, 2012; retrieved from http://ssrn.com/abstract=2160588) -->

## Participants

## Material

## Procedure

### Literature Search

In search of relevant studies, we used Google Scholar as a database.
We used the following search term: **"*prosocial games*" OR "*cooperative games*" AND "*prosocial behavior*'" OR "*cooperative behavior*" OR "*prosocial attitude*" OR "*prosocial behaviour*'" OR "*cooperative behaviour*"** -equilibrium.
The search was conducted on the 22ed of February 2021.
In the first stage, we analyzed 1407 abstracts to find 85 studies that appeared suitable.
Upon further reading, from those 85 articles, we selected 45 that were relevant and had efficient data to be used in the meta-analysis.
Inclusion Criteria: The study had to be published between 2014 and 2021.
The study had to be written in English.
The study had to include either a cooperative or prosocial game as a variable.
The study had to measure at least one social outcome variable, such as prosocial behavior, attitude, or affect.

## Data analysis

Aby zróżnicować heterogeniczność wewnątrz i między artykułami, należy zastosować wielopoziomową (hierarchiczną) metaanalizę, w której efekty zagnieżdżone są w ramach artykułów. Takie podejście umożliwia oszacowanie dwóch komponentów wariancji:
	1.	\tau^2_{within} – wariancja efektów wewnątrz artykułów (np. różne pomiary, grupy, czas pomiaru),
	2.	\tau^2_{between} – wariancja między artykułami (różnice między badaniami jako całościami).

Dzięki temu można obliczyć dwa odpowiadające im współczynniki I² (według np. Viechtaubera, 2021):
	•	I^2_{within} = \frac{\tau^2_{within}}{\tau^2_{within} + \tau^2_{between} + \sigma^2}
	•	I^2_{between} = \frac{\tau^2_{between}}{\tau^2_{within} + \tau^2_{between} + \sigma^2}

Gdzie \sigma^2 to uśredniony błąd pomiaru (sampling variance).


# Results

# Discussion

\newpage

# References

::: {#refs custom-style="Bibliography"}
:::
